### ISSUE TITLE
Anti-Virus Crashes The Program

### ISSUE THREAD

**Issue by xesdoog** [NiiV3AU/YMU#5]
This has nothing to do with the code itself but with how dumb anti-virus software is. The moment you download YimMenu.dll with YMU, the anti-virus places it in quarantine, therefore preventing the program from working properly causing it to crash.
This can be remediated by adding a delay after downloading the file then checking if it's still there, if not, notify the user that it was deleted and they should either disable their anti-virus or add YMU/dll to exceptions. This solution can also be used to check if the game crashes on inject but that's just a QoL improvement so maybe for another time.

We can add a PowerShell script to YMU that will either automatically add the folder path to exceptions on init or add it if a user presses a button or something but there's two issues with this:
1. Having a PS script will probably raise more red flags with anti-viruses.  
2. I only know how to do this with Windows Security using PowerShell. If a user has some kind of bloatware anti-virus, I can't do anything.

I think as a start we should add that delay to prevent the program from crashing then see if we can bypass this issue completely. What do you think?

**Comment by NiiV3AU** [comment]
Does it crash after its downloaded or in the process, e.g. with the progressbar by 50%? The file is downloaded in chunks (128kb) and later on fused into YimMenu.dll so assume after its downloaded. I guess what you mean with delay is that we implement maybe a short sleep duration and then checking if the file is still there and after it exiting the function? It's a bit hard for me to make closer conclusions, simply because I cant replicate this issue. My AV was only quarantining YMU.exe as soon it was built. Its already late for me, so Im going to look into it tomorrow.

**Comment by xesdoog** [comment]
#7 closes this issue.
I tested multiple scenarios including manually deleting the file during the injection process. Feel free to close it if you merge the PR.

**Comment by NiiV3AU** [comment]
Ok im closing the issue, thank you for your support!
